name: New row

on:
  push:
    branches: [ master ]

jobs:
  new-row:
    name: New row
    runs-on: ubuntu-latest
    steps:
    - name: Add row
      id: add-row
      uses: paulholden2/smartsheet-add-row@v1
      with:
        sheet-id: ${{ secrets.SMARTSHEET_SHEET_ID }}
        access-token: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
    - name: Update Col1
      uses: paulholden2/smartsheet-update-row@master
      with:
        sheet-id: ${{ secrets.SMARTSHEET_SHEET_ID }}
        access-token: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
        row-id: ${{ steps.add-row.outputs.row-id }}
        column-name: Col1
        cell-value: Col1 Value
    - name: Update Col2
      uses: paulholden2/smartsheet-update-row@master
      with:
        sheet-id: ${{ secrets.SMARTSHEET_SHEET_ID }}
        access-token: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
        row-id: ${{ steps.add-row.outputs.row-id }}
        column-name: Col2
        cell-value: '10/01/2020'
